spring:
  application:
    name: ACSP-Bot

server:
  port: 6700

application:
  locale:
    resource-name: BotStrings
    default: en
  services:
    backend-base-url: ${ACSP_BACKEND_URL}
  secrets:
    acsp-begin-secret: ${ACSP_BEGIN_KEY}