spring:
  application:
    name: ACSP-Bot

server:
  port: 6700
  ssl:
    enabled: true
    trust-store: classpath:certs/truststore.jks
    trust-store-password: ${SSL_TRUSTSTORE_KEY}
    key-store: classpath:certs/acsp-bot-ssl.p12
    key-store-type: PKCS12
    key-store-password: changeit

application:
  locale:
    resource-name: BotStrings
    default: en
  services:
    backend-base-url: ${ACSP_BACKEND_URL}
  secrets:
    acsp-begin-secret: ${ACSP_BEGIN_KEY}
    acsp-bot-api-secret: ${BOT_API_KEY}