spring:
  application:
    name: ACSP-Backend

  data:
    mongodb:
      uri: ${DB_HOST}
      username: ${DB_USER}
      password: ${DB_PASS}

server:
  port: 8080

application:
  oauth2:
    discord:
      client-id: ${OAUTH_CLIENT_ID}
      client-secret: ${OAUTH_CLIENT_SECRET}
      redirect-uri: ${OAUTH_REDIRECT_URI}