spring:
  application:
    name: ACSP-Backend

  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:27017/acsp

server:
  port: 8080
  ssl:
    enabled: true
    trust-store: classpath:certs/truststore.jks
    trust-store-password: ${SSL_TRUSTSTORE_KEY}
    key-store: classpath:certs/acsp-backend-ssl.p12
    key-store-type: PKCS12
    key-store-password: changeit

application:
  base-url: ${BACKEND_BASE_URL}
  discord-bot-url: ${DISCORD_BOT_URL}
  app-base-url: ${APP_BASE_URL}
  oauth2:
    discord:
      client-id: ${OAUTH_CLIENT_ID}
      client-secret: ${OAUTH_CLIENT_SECRET}
      redirect-uri: ${OAUTH_REDIRECT_URI}
  secrets:
    acsp-begin-secret: ${ACSP_BEGIN_KEY}
  security:
    discord-encryption-key: ${DISCORD_ACCESS_KEY}
    bot-api-key: ${BOT_API_KEY}
    session-key-secret: ${SESSION_KEY_SECRET}
  keystore:
    path: ${KEYSTORE_PATH}
    password: ${KEYSTORE_KEY}
    alias: sessionKeys