spring:
  application:
    name: ACSP-Backend

  data:
    mongodb:
      uri: mongodb://${DB_USER}:${DB_PASS}@${DB_HOST}:27017/acsp

server:
  port: 8080

application:
  base-url: ${BACKEND_BASE_URL}
  oauth2:
    discord:
      client-id: ${OAUTH_CLIENT_ID}
      client-secret: ${OAUTH_CLIENT_SECRET}
      redirect-uri: ${OAUTH_REDIRECT_URI}
  secrets:
    acsp-begin-secret: ${ACSP_BEGIN_KEY}
  security:
    discord-encryption-key: ${DISCORD_ACCESS_KEY}